### ISSUE TITLE
Bug: UI label is unclear 

### ISSUE THREAD

**Issue by Shawnli3287** [kaazii/EECS2311#42] opened 2021-03-24 02:25 UTC
Name
Interface gui text label problem

Description
The text of the instrument label is unclear and some part is hidden

Steps to reproduce
Run the main as java application, on the main interface UI

Expected result
Simple and well-arranged user interface UI

Actual result
For instrument label is unclear and it is been Hidden

Priority
Lower-middle

Status
Ready for development.

Screenshot
![image](https://user-images.githubusercontent.com/46501533/112245145-b8159480-8c26-11eb-83d6-52da076f1eff.png)

**Comment by zhouziqi13** [comment] 2021-03-24 16:51
@Li-wenxuan-216374324 should be resolved in the new release. Keeping this for future release.

**Comment by zhouziqi13** [comment] 2021-03-24 17:14
@zhoudoris13 to test

**Comment by zhouziqi13** [comment] 2021-04-03 15:12
#42 Cannot reproduce. Closed

**Closed as completed by zhouziqi13** 2021-04-03 15:12 UTC
